apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-calc-service
  namespace: fintech-uat-metis-team
  labels:
    app: fin-calc-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate # recreate is second option and is without next 3 lines
    rollingUpdate:
      maxSurge: 1       # how many pods we can add at a time
      maxUnavailable: 1 # maxUnavailable define how many pods can be unavailable during the rolling update
  selector:
    matchLabels:
      app: fin-calc-service
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      labels:
        app: fin-calc-service
        deploysphere_health: "true"
    spec:
      imagePullSecrets:
        - name: fintech-docker-secret
      containers:
        - name: fin-calc-service
          image: metis-team-docker-registry.fintechchallenge.pl/metis-team/fin-calc-service:latest
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8080
            - name: management
              containerPort: 9090
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 120
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 70
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fin-calc-service
  labels:
    app: fin-calc-service
    visualize: "true"
    prometheus_monitoring: "true"
spec:
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: api
  selector:
    app: fin-calc-service
---









---
# Note: in a kubernetes secret the string (e.g. generated by htpasswd) must be base64-encoded first.
# To create an encoded user:password pair, the following command can be used:
# htpasswd -nb user password | openssl base64

apiVersion: v1
kind: Secret
metadata:
  name: fintech-uat-metis-team-basic-auth-secret
  namespace: fintech-uat-metis-team

data:
  users: |
    bWV0aXNtZW1iZXI6JGFwcjEkZFg1OFFGY04kNi41enhKc1I0dzJMRGhoTG1XUFU3MAoK
#encryped username: example, with password: example

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: fintech-uat-metis-team-basic-auth-middleware
  namespace: fintech-uat-metis-team
spec:
  basicAuth:
    secret: fintech-uat-metis-team-basic-auth-secret
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: fin-calc-service
  namespace: fintech-uat-metis-team
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`fin-calc-service.metis-team.uat.fintechchallenge.pl`)
      middlewares:
        - name: fintech-uat-metis-team-basic-auth-middleware
          namespace: fintech-uat-metis-team
      services:
        - kind: Service
          name: fin-calc-service
          namespace: fintech-uat-metis-team
          passHostHeader: true
          port: 8080
          scheme: http
  tls:
    options:
      namespace: fintech-uat-metis-team
    certResolver: hltech
    domains:
      - main: fin-calc-service.metis-team.uat.fintechchallenge.pl
